### ISSUE TITLE
Add support for vertical integrals

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaCore.jl#748] opened 2022-06-06 23:24 UTC
**Is your feature request related to a problem? Please describe.**

We need vertical integrals in various places, including TurbulenceConvection and ClimaAtmos. The current `sum` is just a volume integral which is equivalent for a single column of area 1, but definitely not what we want to use for things like liquid water path.

Please link to any related issues/PRs.

**Describe the solution you'd like**

Define both
 - `vertical∫` that computes a vertical definite integral
 - `vertical_indefinite∫` that computes a vertical indefinite integral

**Describe alternatives you've considered**

**Additional context**

**Comment by simonbyrne** [comment] 2022-06-07 23:10
As discussed on slack, I think definite integrals are well-defined: you sum multiplying by the dxdxi[3,3] term, and return a field on the horizontal space.

For indefinite integrals, I think we should return a face-aligned field? I think we also want an option for upward or downward.

**Comment by simonbyrne** [comment] 2022-09-27 21:29
Duplicate of #693.

**Closed by simonbyrne** 2022-09-27 21:29 UTC
Labels: enhancement
